version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 042729137627.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - docker build -t predictium:latest .
      - docker tag predictium:latest 042729137627.dkr.ecr.us-east-2.amazonaws.com/predictium:latest
  post_build:
    commands:
      - docker push 042729137627.dkr.ecr.us-east-2.amazonaws.com/predictium:latest
